export default {
  SERVICE_LOAD_EVENTS: 'SERVICE_LOAD_EVENTS',
  SET_CURRENT_DATE: 'SET_CURRENT_DATE',
  SERVICE_CREATE_EVENT: 'SERVICE_CREATE_EVENT',
  CREATE_EVENT: 'CREATE_EVENT',
  SHOW_CREATE_NEW_EVENT_MODAL: 'SHOW_CREATE_NEW_EVENT_MODAL',
  HIDE_CREATE_NEW_EVENT_MODAL: 'HIDE_CREATE_NEW_EVENT_MODAL'
};